# Generated by Django 5.1.6 on 2025-03-05 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название алгоритма')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название бренда')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название монеты')),
                ('api_title', models.CharField(blank=True, max_length=250, verbose_name='Например bitcoin')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок параграфа')),
            ],
            options={
                'verbose_name': 'Параграф для новоти',
                'verbose_name_plural': 'Параграфы для новости',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='news/news_detail/', verbose_name='Фото в кoHце параграфа')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ник в тг (@nickname)')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка на аккаунт менеджера')),
            ],
        ),
        migrations.CreateModel(
            name='Asic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=250, verbose_name='Полное название')),
                ('title', models.CharField(max_length=250, verbose_name='Краткое название')),
                ('hash', models.IntegerField(verbose_name='Хэшрейт')),
                ('hash_title', models.CharField(choices=[('Th', 'Th/s'), ('Gh', 'Gh/s'), ('Mh', 'Mh/s')], max_length=2, verbose_name='Единица хеша')),
                ('power', models.IntegerField(verbose_name='Потребление')),
                ('price_usdt', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стоимость в usdt')),
                ('algo', models.CharField(max_length=250, verbose_name='Алгоритм')),
                ('hash_unit', models.CharField(blank=True, max_length=4, verbose_name='Написать что то одно: TH/s | GH/s | MH/s')),
                ('multiplier', models.FloatField(blank=True, default=1.0, verbose_name='Множитель')),
                ('hot', models.BooleanField(default=False, verbose_name='Горячее предложение')),
                ('btc', models.BooleanField(default=True, verbose_name='Асик на биткоин?')),
                ('popular', models.BooleanField(default=False, verbose_name='Популярный асик')),
                ('home_mining', models.BooleanField(default=False, verbose_name='Домашний асик')),
                ('classic', models.BooleanField(default=False, verbose_name='Проверенная классика')),
                ('profitable', models.BooleanField(default=False, verbose_name='Наибольшая доходность')),
                ('image', models.ImageField(blank=True, upload_to='asics_main_photo/', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('algo_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.algo', verbose_name='АЛГОРИТМ')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand', verbose_name='Бренд')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin', verbose_name='Монета')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок новости')),
                ('description', models.TextField(blank=True, verbose_name='Предисловие (небольшое)')),
                ('img', models.ImageField(upload_to='news/', verbose_name='Основное фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликованна?')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('sections', models.ManyToManyField(to='api.newssection', verbose_name='Секции с параграфами')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='newssection',
            name='paragraph',
            field=models.ManyToManyField(to='api.paragraph', verbose_name='Параграфы'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200, verbose_name='Ссылка на Facebook')),
                ('instagram', models.CharField(max_length=200, verbose_name='Ссылка на Instagram')),
                ('telegram', models.CharField(max_length=200, verbose_name='Ссылка на Telegram')),
                ('olx', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на OLX')),
                ('price_list', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на прайс лист (google table)')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('img', models.ImageField(upload_to='contacts/', verbose_name='Фото с гугл карт(или других карт)')),
                ('managers', models.ManyToManyField(to='api.telegrammanagers', verbose_name='Менеджеры')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
